### PR TITLE
Fix Big Sur support

### LINKED ISSUE #80: add support for Big Sur
I have tested manually to create a virtualbox-based vm. and it works. The script does not accomodate for it. 

May create PR to add it.

### LINKED ISSUE #85: hdiutil: attach failed - No such file or directory (Big Sur does not have InstallESD.dmg)
```
% ./macos-virtualbox-vm/prepare-iso.sh

Mount the installer image
--------------------------------------------------------------------------
$ hdiutil attach /Applications/Install macOS Big Sur.app/Contents/SharedSupport/InstallESD.dmg -noverify -nobrowse -mountpoint /Volumes/install_app
hdiutil: attach failed - No such file or directory
```

This is not the same cause as https://github.com/geerlingguy/macos-virtualbox-vm/issues/64

```
% find /Applications/Install*/Contents/SharedSupport -ls
15070751        0 drwxr-xr-x    3 root             wheel                  96 Aug 25 14:17 /Applications/Install macOS Big Sur.app/Contents/SharedSupport
15070752 24298672 -rw-r--r--    1 root             wheel            12440916552 Aug 25 14:22 /Applications/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg

% find /Applications/Install* -iname '*dmg' -ls
15070752 24298672 -rw-r--r--    1 root             wheel            12440916552 Aug 25 14:22 /Applications/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg
```

### PR DESCRIPTION
**Pull request by ansonhoyt**
Updates the createISO function for Big Sur and notes increased disk requirements for Big Sur.

I tested with Big Sur, and successfully installed the `BigSur.iso` it produced. I *didn't* re-test any other macOS releases.

This finishes up the start in #84.

Fixes #85, fixes #80

### CODE REVIEW

File: prepare-iso.sh [hunk 1]
```diff
@@ -26,11 +26,23 @@ function createISO()
...
 
+    echo
+    echo Create ${isoName} blank ISO image with a Single Partition - Apple Partition Map
+    echo --------------------------------------------------------------------------
+    # Just in case - delete any previous sparseimage
+    [ -e /tmp/${isoName}.sparseimage ] && rm -f /tmp/${isoName}.sparseimage
+    # increased size to 16G - 8G is too small for Catalina
+    echo $ hdiutil create -o /tmp/${isoName} -size 16g -layout SPUD -fs HFS+J -type SPARSE
+    hdiutil create -o /tmp/${isoName} -size 16g -layout SPUD -fs HFS+J -type SPARSE
+
```
Comment (ansonhoyt) [inline prepare-iso.sh:37]: Note, this block was just moved up since Big Sur will mount this as the installer image, `install_app`.

**Comment by kiding** [comment]
A very minor note: Adding "Big Sur" support comments at the top of `prepare-iso.sh` and `README.md` would be great.

**Comment by NicholasTD07** [comment]
Nice man! Thanks for the great work! I was just looking for this.
